sudo: true
language: python

python:
    - "3.4"
    - "3.5"

install:
    - pip install tox-travis coveralls
    - sudo apt-get install unixodbc-dev
script:
    - tox
after_success:
    - coveralls -v

notifications:
    email: false
